name: Vite React App CI/CD on Push to develop

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest 

    steps:
    
    - name: 1. Checkout Repository Code
      uses: actions/checkout@v4 

    - name: 2. Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: '22' 
        cache: 'npm'       

    - name: 3. Install Project Dependencies
      run: npm install


    - name: 4. Build Vite React App
      run: npm run build
      
    - name: 5. Clean Up Old Deployment (Delete dist)
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            TARGET_DIR="/var/www/html/nttn-monitoring-application/frontend"
            DELETE_PATH="${TARGET_DIR}/dist"
              
            echo "Attempting to remove old dist folder at ${DELETE_PATH}"
              
            if [ -d "${DELETE_PATH}" ]; then
               sudo rm -rf "${DELETE_PATH}" 
               echo "Old dist folder deleted successfully."
            else
               echo "Old dist folder not found. Clean up skipped."
            fi

    - name: 6. Deploy 'dist' folder to Server via SSH 
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        source: "dist" 
        target: "/var/www/html/nttn-monitoring-application/frontend"
        
    - name: 7. Post-Deployment: Reload Nginx and Confirm via SSH
      uses: appleboy/ssh-action@v1.0.3 
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        
        script: |
          echo "Successfully deployed to /var/www/html/nttn-monitoring-application/frontend"
          sudo systemctl reload nginx
          echo "Nginx has been reloaded. Deployment complete."

